### ISSUE TITLE
Adicionar ci/cd | coveralls | requires

### ISSUE THREAD

**Issue by riquellopes** [riquellopes/onde-eles-investem#5]
Adicionar ferramentas para cuidar da saude do código.

* https://coveralls.io/
* https://requires.io/
* https://travis-ci.org/

**Comment by JorgeMadson** [comment]
Vou fazer um tests automatizados pra cada commit no pull request, vou mandar aqui, aí se vc curtir aprova meu pull request?

**Comment by JorgeMadson** [comment]
Adicionei um pull request #9
